import {useState} from 'react'
import {Link} from 'react-router-dom'
import {Activity,Clock,Eye,TrendingUp,Users,WalletCards} from 'lucide-react'

const nav=[['/dashboard','Overview'],['/dashboard/content','Content'],['/dashboard/analytics','Analytics'],['/wallet','Earnings'],['/dashboard','Schedule'],['/settings','Settings']]
const ranges={
  '7 days':{views:'24.8K',watch:'3.2K hrs',followers:'+486',average:'1,420',earnings:'KES 8.4K',change:'+18%',bars:[42,58,49,76,63,88,72]},
  '30 days':{views:'94.6K',watch:'12.7K hrs',followers:'+1,842',average:'1,386',earnings:'KES 32.8K',change:'+12%',bars:[34,48,41,55,62,57,71,66,79,73,86,82]},
  '3 months':{views:'286K',watch:'38.4K hrs',followers:'+5,210',average:'1,274',earnings:'KES 96.5K',change:'+24%',bars:[28,33,39,45,41,52,59,63,58,72,78,84]},
  '12 months':{views:'1.2M',watch:'161K hrs',followers:'+21.4K',average:'1,108',earnings:'KES 418K',change:'+68%',bars:[18,26,24,35,42,47,54,61,69,73,82,91]}
} as const
type Range=keyof typeof ranges
export function AnalyticsPage(){const [range,setRange]=useState<Range>('30 days');const data=ranges[range];const metrics=[['Total views',data.views,Eye],['Watch time',data.watch,Clock],['Followers gained',data.followers,TrendingUp],['Avg. concurrent',data.average,Users],['Estimated earnings',data.earnings,WalletCards]] as const;return <div className="page analytics-page"><nav className="studio-subnav" aria-label="Creator Dashboard">{nav.map(([to,label])=><Link className={label==='Analytics'?'active':''} to={to} key={label}>{label}</Link>)}</nav><header className="analytics-title"><div><span className="section-kicker">CREATOR DASHBOARD</span><h1>Analytics</h1><p>Understand how your streams and community are growing.</p></div><div className="analytics-ranges" aria-label="Analytics timeframe">{(Object.keys(ranges) as Range[]).map(x=><button className={range===x?'active':''} onClick={()=>setRange(x)} key={x}>{x}</button>)}</div></header><div className="analytics-stats">{metrics.map(([label,value,Icon])=><article key={label}><Icon/><span>{label}</span><strong>{value}</strong><small>{data.change} vs previous period</small></article>)}</div><div className="analytics-grid"><section className="analytics-chart"><header><div><span>VIEWERSHIP</span><h2>Views over time</h2></div><b>{data.views}</b></header><div className="bar-chart" aria-label={`Viewership chart for ${range}`}>{data.bars.map((height,i)=><div key={i}><i style={{height:`${height}%`}}/><span>{range==='7 days'?['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][i]:i%2===0?`${i+1}`:''}</span></div>)}</div></section><section className="analytics-breakdown"><span>DISCOVERY</span><h2>How viewers found you</h2>{[['Following feed',42],['Browse',28],['Recommendations',19],['Direct links',11]].map(([label,value])=><div key={label}><p><span>{label}</span><b>{value}%</b></p><i><em style={{width:`${value}%`}}/></i></div>)}</section><section className="analytics-breakdown"><span>TOP CONTENT</span><h2>Best-performing streams</h2>{['React state without stress','Building a biashara app','Portfolio reviews live'].map((title,i)=><p className="top-content" key={title}><span><b>{i+1}</b>{title}</span><strong>{[23640,18420,12780][i].toLocaleString()} views</strong></p>)}</section><section className="analytics-breakdown"><span>AUDIENCE</span><h2>Community snapshot</h2><div className="audience-row"><Activity/><p><b>8:00–10:00 PM</b><span>Most active viewing time</span></p></div><div className="audience-row"><Users/><p><b>68% returning</b><span>Viewer loyalty</span></p></div></section></div><p className="demo-note">All analytics shown are simulated demo data.</p></div>}
