import {useMemo,useState} from 'react'
import {Link,useParams} from 'react-router-dom'
import {ArrowRight,Bell,CalendarDays,Check,Play,Search,Users} from 'lucide-react'
import {categories,categoryMeta,clips,creatorById,creators,events,streams} from '../data'
import {CategoryCard,ClipCard,CreatorCard,EmptyState,FilterChips,FollowButton,LiveBadge,StreamCard,ViewerCount} from '../components'
import {useApp} from '../context'
export function HomePage(){const featured=streams[0],c=creatorById(featured.creatorId);const {toast}=useApp();return <div className="page"><section className="hero"><div className="hero-copy"><span className="eyebrow">{`THE 254, LIVE RIGHT NOW`}</span><h1>Kenya is<br/><em>live.</em></h1><p>Watch the stories, sounds, games and conversations shaping the culture.</p><div className="hero-actions"><Link className="btn btn-white" to={`/watch/${featured.id}`}><Play/> Watch now</Link><FollowButton creatorId={c.id}/></div><div className="hero-creator"><span className="verified">✓</span><b>{c.name}</b><span>{featured.category}</span></div></div><Link className="hero-preview" to={`/watch/${featured.id}`} style={{'--accent':featured.accent} as React.CSSProperties}><LiveBadge/><ViewerCount count={featured.viewers}/><div className="signal"><i/><i/><i/><i/></div><div className="hero-preview-info"><span>{featured.title}</span><small>{featured.duration} live</small></div></Link></section><Section title="Live now" link="/browse"><div className="stream-grid">{streams.slice(0,8).map(s=><StreamCard key={s.id} stream={s}/>)}</div></Section><Section title="Popular on Jukwaa" link="/browse#categories"><div className="category-grid">{categoryMeta.map(x=><CategoryCard key={x.name} {...x}/>)}</div></Section><Section title="Don’t miss it"><div className="event-grid">{events.map(([name,date,time])=><article className="event" key={name}><CalendarDays/><div><span>{date} · {time}</span><h3>{name}</h3></div><button onClick={()=>toast(`Reminder set for ${name}`)}><Bell/> Remind me</button></article>)}</div></Section></div>}
function Section({title,link,children}:{title:string;link?:string;children:React.ReactNode}){return <section className="section"><div className="section-head"><h2>{title}</h2>{link&&<Link to={link}>See all <ArrowRight/></Link>}</div>{children}</section>}
export function BrowsePage(){const [tab,setTab]=useState('Live streams'),[q,setQ]=useState(''),[category,setCategory]=useState('All'),[lang,setLang]=useState('All'),[sort,setSort]=useState('Recommended');const list=useMemo(()=>streams.filter(s=>(category==='All'||s.category===category)&&(lang==='All'||s.language===lang)&&(s.title+' '+creatorById(s.creatorId).name).toLowerCase().includes(q.toLowerCase())).sort((a,b)=>sort==='Most viewers'?b.viewers-a.viewers:sort==='Newest'?a.created-b.created:0),[q,category,lang,sort]);return <div className="page"><PageTitle eyebrow="FIND YOUR CROWD" title="Browse Jukwaa" text="Live stories, games and communities from every corner of Kenya."/><FilterChips options={['Live streams','Creators','Categories']} value={tab} onChange={setTab}/><div className="browse-tools"><label className="search wide"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search streams and creators"/></label><select aria-label="Category" value={category} onChange={e=>setCategory(e.target.value)}><option>All</option>{categories.map(x=><option key={x}>{x}</option>)}</select><select aria-label="Language" value={lang} onChange={e=>setLang(e.target.value)}>{['All','English','Kiswahili','Sheng','Kikuyu','Luo','Kalenjin','Other'].map(x=><option key={x}>{x}</option>)}</select><select aria-label="Sort results" value={sort} onChange={e=>setSort(e.target.value)}>{['Recommended','Most viewers','Newest'].map(x=><option key={x}>{x}</option>)}</select></div>{tab==='Live streams'&&(list.length?<div className="stream-grid">{list.map(s=><StreamCard key={s.id} stream={s}/>)}</div>:<EmptyState title="No streams found" text="Try a different filter or search term."/>)}{tab==='Creators'&&<div className="creator-grid">{creators.filter(c=>c.name.toLowerCase().includes(q.toLowerCase())).map(c=><CreatorCard key={c.id} creator={c}/>)}</div>}{tab==='Categories'&&<div className="category-grid">{categoryMeta.map(x=><CategoryCard key={x.name} {...x}/>)}</div>}</div>}
export function CategoryPage(){const {categoryName}=useParams();const name=decodeURIComponent(categoryName??'');const list=streams.filter(s=>s.category===name);return <div className="page"><PageTitle eyebrow="CATEGORY" title={name} text={`${list.length} channels live now`}/><div className="stream-grid">{list.map(s=><StreamCard key={s.id} stream={s}/>)}</div></div>}
export function FollowingPage(){const {followed}=useApp();const followedCreators=creators.filter(c=>followed.has(c.id));const live=streams.filter(s=>followed.has(s.creatorId));if(!followed.size)return <div className="page"><PageTitle eyebrow="YOUR COMMUNITY" title="Following"/><EmptyState title="Your front row is waiting" text="Follow creators to see their streams and schedules here." action={<Link className="btn btn-accent" to="/browse">Find creators</Link>}/></div>;return <div className="page"><PageTitle eyebrow="YOUR COMMUNITY" title="Following" text={`${followed.size} creators in your circle`}/><Section title="Live now"><div className="stream-grid">{live.map(s=><StreamCard key={s.id} stream={s}/>)}</div></Section><Section title="Offline creators"><div className="creator-grid">{followedCreators.filter(c=>!c.live).map(c=><CreatorCard key={c.id} creator={c}/>)}</div></Section><Section title="Coming up"><div className="schedule-list">{followedCreators.slice(0,3).map((c,i)=><div key={c.id}><span>{['Tomorrow · 8:00 PM','Saturday · 3:00 PM','Monday · 7:30 PM'][i]}</span><b>{c.name} is going live</b><button><Check/> Following</button></div>)}</div></Section></div>}
export function ClipsPage(){const [filter,setFilter]=useState('Trending');return <div className="page"><PageTitle eyebrow="THE BEST MOMENTS" title="Clips" text="Big plays, funny moments and culture in under a minute."/><FilterChips options={['Trending','Today','This week','Following']} value={filter} onChange={setFilter}/><div className="clip-grid">{clips.map(c=><ClipCard key={c.id} clip={c}/>)}</div></div>}
export function PageTitle({eyebrow,title,text}:{eyebrow:string;title:string;text?:string}){return <header className="page-title"><span>{eyebrow}</span><h1>{title}</h1>{text&&<p>{text}</p>}</header>}
